version: "3.7"

services:

  dashboard:
    image: nathaliesaintgeours/demo:${APP_VERSION}
    container_name: demo_dashboard
    ports:
      - "8050:8888"
    environment:
      - TARGET=LIVE
      - MODEL_API=http://model:8080/invocations
    restart: unless-stopped

  model:
    image: nathaliesaintgeours/demo_mlflow_model:${MODEL_VERSION}
    container_name: demo_model
    ports:
        - "5001:8080"
    restart: unless-stopped