name: Deploy to production server

on:
  workflow_dispatch

env:
    APP_NAME: demo
    APP_VERSION: latest

    MODEL_NAME: demo_mlflow_model
    MODEL_VERSION: latest

    DOCKER_USER: nathaliesaintgeours
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    SSH_HOST: 18.134.221.50
    SSH_USERNAME: bitnami
    SSH_KEY: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY }}

jobs:

   publish_docker:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: Build Docker container
       run: docker build -t $DOCKER_USER/$APP_NAME:$APP_VERSION .

     - name: Docker login
       run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

     - name: Publish dockerized app on Docker Hub
       run: docker push $DOCKER_USER/$APP_NAME:$APP_VERSION

   publish_mlflow_model:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: Set up Python 3.9
       uses: actions/setup-python@v2
       with:
         python-version: 3.9

     - name: Install mlflow
       run: |
         python -m pip install --upgrade pip
         pip install mlflow

     - name: Build Docker container from MLflow model
       run: |
         mlflow models build-docker -m  ${GITHUB_WORKSPACE}/mlflow_model -n "$MODEL_NAME"

     - name: Docker login
       run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

     - name: Publish dockerized model on Docker Hub
       run: |
         docker tag $MODEL_NAME $DOCKER_USER/$MODEL_NAME:$MODEL_VERSION
         docker push $DOCKER_USER/$MODEL_NAME:$MODEL_VERSION

   deploy_production:
     runs-on: ubuntu-latest

     needs: [publish_docker, publish_mlflow_model]

     steps:
     - uses: actions/checkout@v2

     - name: Copy Docker Compose file to production server (through SSH)
       uses: appleboy/scp-action@master
       with:
         host: $SSH_HOST
         username: $SSH_USERNAME
         key: $SSH_KEY
         source: "docker-compose.yml"
         target: "~"

     - name: Run Docker containers on production server (through SSH)
       uses: appleboy/ssh-action@master
       with:
         host: $SSH_HOST
         username: $SSH_USERNAME
         key: $SSH_KEY
         envs: APP_VERSION, MODEL_VERSION, SSH_HOST
         script: |
           cd ~
           APP_VERSION=$APP_VERSION MODEL_VERSION=$MODEL_VERSION SSH_HOST=$SSH_HOST docker-compose down
           APP_VERSION=$APP_VERSION MODEL_VERSION=$MODEL_VERSION SSH_HOST=$SSH_HOST docker-compose pull
           APP_VERSION=$APP_VERSION MODEL_VERSION=$MODEL_VERSION SSH_HOST=$SSH_HOST docker-compose up -d